server:
  port: 8050

spring:
  rabbitmq:
    addresses: 192.168.99.100
    host: 192.168.99.100
    port: 5762
    username: guest
    password: guest
  application:
    name: hubttservice
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.99.100:5432/hubtt_db
    password: postgres
    username: postgres
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: 
          use_jdbc_metadata_defaults: false 
  redis:
    port: 6379
    host: 192.168.99.100
    password: Redis2019!
  data:
    redis:
      repositories:
        enabled: true

mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml

api: 
  maxTransactionDetail: 10
  rabbitSaveTransaction : rabbit-save-transaction
  actions: 
    - withdraw